"""add coluna descricao

Revision ID: c7a76b96cd7f
Revises: 3cf51a206589
Create Date: 2026-04-07 16:23:57.739660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a76b96cd7f'
down_revision: Union[str, Sequence[str], None] = '3cf51a206589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descricao', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'descricao')
    # ### end Alembic commands ###
